Generate gitlab composer repo

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -34,16 +34,22 @@ pages:
     paths:
       - public
 
-# Trigger a rebuild of the packagist repo
 deploy:
   stage: deploy
-  only:
-    variables:
-      - $packagist_token
-  allow_failure: true
-  image: alpine:3.7
-  before_script:
-    - apk update
-    - apk add git curl
+  image: curlimages/curl:latest
+  variables:
+    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
   script:
-    - "curl -X POST -F token=${packagist_token} -F ref=master https://gitlab.com/api/v4/projects/7511938/trigger/pipeline"
+    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
+    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
+    - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
+    - code=$(echo "$response" | tail -n 1)
+    - body=$(echo "$response" | head -n 1)
+    # Output state information - this fails the job if the server does not respond with OK
+    - if [ $code -eq 201 ]; then
+        echo "Package created - Code $code - $body";
+      else
+        echo "Could not create package - Code $code - $body";
+        exit 1;
+      fi
+
